apiVersion: v1
kind: Service
metadata:
    name: hello-pythonapp-service
spec:
    selector:
        app: hello-pythonapp
    type: LoadBalancer
    ports:
      - name: http
        port: 80
        targetPort: 80
        protocol: TCP