apiVersion: v1
kind: Service
metadata:
    name: webapp-service
spec:
    selector:
        app: webapp
    type: LoadBalancer
    ports:
      - name: http
        port: 80
        targetPort: 8090
        protocol: TCP